### ISSUE TITLE
The pso_CopyParameter errors when missing optionional param value

### ISSUE THREAD

**Issue by nsmythili** [percussion/PSOToolkit#37]
To use pso_CopyParameter for a given field , only source and destination params are required.  Just giving these two field values in configuration causing "An internal error (end-condition) was encountered. An unexpected exception occurred:
An unexpected exception occurred. The reason was: For input string: "". Please consult the log for further information.. ".  Just giving value of fieldsize param avoids this exception.  It looks like this extension is acting as if fieldsize is a required field.

 

To reproduce:

1. In OOB where psotoolkit is installed edit a content type field to use pso_CopyParameter extension in Input Transform tab of content type properties tab.
2. Give source and destination param
3. Create item of this content type in content explorer and would notice this exception on save.

4. Edit the extension to add fieldsize param and that would save the item without any issue.

**Comment by SDKelly** [comment]
Unable to reproduce the issue. I believe we can close this issue for now and reopen if necessary.

**Comment by nsmythili** [comment]
This issue no longer appears to exists.  Must have been fixed with the recent builds.  Closing.

**Comment by nsmythili** [comment]
Internal comment from Nate:

Nate Chadwick added a comment - 23/Oct/15 12:24 PM

I believe this is fixed by issue #31 in the toolkit project.
